'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MediaMinistry.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property App_Icon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("App_Icon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BannerImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BannerImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property credentials() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("credentials", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''&lt;link rel=&quot;stylesheet&quot; href=&quot;https://sppbc.hopto.org/css/emails.css&quot;
        '''&lt;/head&gt;
        '''&lt;body&gt;
        '''
        '''&lt;p&gt;Hello {0},&lt;/p&gt;&lt;br&gt;
        '''
        '''{1}
        '''&lt;hr&gt;
        '''
        '''&lt;p&gt;&lt;strong&gt;Elder Bryon K Miller, Pastor&lt;/strong&gt;&lt;br&gt;
        '''		St. Paul Primitive Baptist Church&lt;br&gt;
        '''		Email Listening Ministry&lt;br&gt;
        '''		2209 East 14th Street&lt;br&gt;
        '''		Austin, TX. 78702&lt;/p&gt;
        '''&lt;/body&gt;
        '''&lt;/html&gt;.
        '''</summary>
        Friend ReadOnly Property customMessageTemplate() As String
            Get
                Return ResourceManager.GetString("customMessageTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''&lt;link rel=&quot;stylesheet&quot; href=&quot;https://sppbc.hopto.org/css/emails.css&quot;
        '''&lt;/head&gt;
        '''&lt;body&gt;
        '''
        '''&lt;p&gt;Hello {0},&lt;/p&gt;&lt;br&gt;
        '''
        '''{1}&lt;br&gt;
        '''
        '''&lt;a href=&quot;{2}&quot;&gt;Drive File&lt;/a&gt;
        '''
        '''&lt;hr&gt;
        '''
        '''&lt;p&gt;&lt;strong&gt;Elder Bryon K Miller, Pastor&lt;/strong&gt;&lt;br&gt;
        '''		St. Paul Primitive Baptist Church&lt;br&gt;
        '''		Email Listening Ministry&lt;br&gt;
        '''		2209 East 14th Street&lt;br&gt;
        '''		Austin, TX. 78702&lt;/p&gt;
        '''&lt;/body&gt;
        '''&lt;/html&gt;.
        '''</summary>
        Friend ReadOnly Property customMessageWithDriveLink() As String
            Get
                Return ResourceManager.GetString("customMessageWithDriveLink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://drive.google.com/file/d/{0}/view?usp=sharing.
        '''</summary>
        Friend ReadOnly Property DriveShareLink() As String
            Get
                Return ResourceManager.GetString("DriveShareLink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ErrorImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ErrorImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HidePasswordIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HidePasswordIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Loading_Loop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Loading_Loop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Loading_Loop_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Loading_Loop_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Loading_Loop_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Loading_Loop_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Logout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!Doctype html&gt;
        '''&lt;html&gt;
        '''    &lt;head&gt;
        '''        &lt;link rel=&quot;stylesheet&quot; href=&quot;https://sppbc.herbivore.site/manager/css/emails.css&quot;&gt;
        '''    &lt;/head&gt;
        '''    &lt;body&gt;
        '''        &lt;p&gt;Blessings To You {0},&lt;/p&gt;
        '''
        '''		&lt;p&gt;Welcome to the St. Paul Primitive Baptist Church Email Listening Ministry. Thank you for becoming a Subscriber. You will receive Sunday&apos;s Messages from the St. Paul Primitive Baptist Church, Austin, TX. Morning Service each week; where Elder Bryon K. Miller is the Pastor. You will Receive your Sunday Morning Mes [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property newListener() As String
            Get
                Return ResourceManager.GetString("newListener", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''  &lt;head&gt;
        '''    &lt;link rel=&quot;stylesheet&quot; href=&quot;https://sppbc.herbivore.site/manager/css/emails.css&quot; /&gt;
        '''  &lt;/head&gt;
        '''  &lt;body&gt;
        '''    &lt;div&gt;
        '''      &lt;p&gt;Blessings To You, {0}&lt;/p&gt;
        '''
        '''
        '''      &lt;p&gt;
        '''        Welcome to the new &lt;strong&gt;BK &amp; AR Miller Ministries Email Listening&lt;/strong&gt;, formerly St. Paul Primitive Baptist Church Email Listening Ministry. Thank you for being a subscriber.
        '''        Over the last year I suffered a major stroke, but thanks be to God, I am still here and alive!
        '''        M [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property newSermon() As String
            Get
                Return ResourceManager.GetString("newSermon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^(?:(?:\+?1\s*(?:[.-]\s*)?)?(?:\(\s*([2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9])\s*\)|([2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9]))\s*(?:[.-]\s*)?)?([2-9]1[02-9]|[2-9][02-9]1|[2-9][02-9]{2})\s*(?:[.-]\s*)?([0-9]{4})(?:\s*(?:#|x\.?|ext\.?|extension)\s*(\d+))?$.
        '''</summary>
        Friend ReadOnly Property PhoneRegex() As String
            Get
                Return ResourceManager.GetString("PhoneRegex", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!Doctype html&gt;
        '''&lt;html&gt;
        '''    &lt;head&gt;
        '''        &lt;link rel=&quot;stylesheet&quot; href=&quot;https://sppbc.herbivore.site/manager/css/emails.css&quot;&gt;
        '''    &lt;/head&gt;
        '''    &lt;body&gt;
        '''
        '''	&lt;p&gt;Greetings {0},&lt;/p&gt;
        '''
        '''        &lt;p&gt;Thank you for your blessing of {1:C} for {2}.&lt;/p&gt;
        '''
        '''		&lt;p&gt;Thank You For Your Support.&lt;/p&gt;
        '''
        '''		&lt;p&gt;Be Blessed.&lt;/p&gt;
        '''
        '''		&lt;p class=&quot;center&quot;&gt;&lt;strong&gt;WE LOVE YOU AND AIN&apos;T NOTHING YOU CAN DO ABOUT IT!&lt;/strong&gt;&lt;br&gt;&lt;/p&gt;
        '''
        '''		&lt;hr&gt;
        '''		
        '''		&lt;p&gt;&lt;strong&gt;Elder Bryon K Miller, Pastor&lt;/strong&gt;&lt;br&gt;
        '''		St. Paul Primitive Baptist Church [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property receipt() As String
            Get
                Return ResourceManager.GetString("receipt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ShowPasswordIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ShowPasswordIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
