// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:4.0.30319.42000
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Drawing;
using System.Runtime.CompilerServices;
using Microsoft.VisualBasic;
using Microsoft.VisualBasic.CompilerServices;
using SPPBC.M3Tools.Types;

namespace MediaMinistry.My
{

    [CompilerGenerated()]
    [System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
    public sealed partial class MySettings : System.Configuration.ApplicationSettingsBase
    {

        private static MySettings defaultInstance = (MySettings)Synchronized(new MySettings());

        #region My.Settings Auto-Save Functionality
        /* TODO ERROR: Skipped IfDirectiveTrivia
        #If _MyType = "WindowsForms" Then
        */
        private static bool addedHandler;

        private static object addedHandlerLockObject = new object();

        [DebuggerNonUserCode()]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        private static void AutoSaveSettings(object sender, EventArgs e)
        {
            if (MyProject.Application.SaveMySettingsOnExit)
            {
                MySettingsProperty.Settings.Save();
            }
        }
        /* TODO ERROR: Skipped EndIfDirectiveTrivia
        #End If
        */
        #endregion

        public static MySettings Default
        {
            get
            {

                /* TODO ERROR: Skipped IfDirectiveTrivia
                #If _MyType = "WindowsForms" Then
                */
                if (!addedHandler)
                {
                    lock (addedHandlerLockObject)
                    {
                        if (!addedHandler)
                        {
                            MyProject.Application.Shutdown += AutoSaveSettings;
                            addedHandler = true;
                        }
                    }
                }
                /* TODO ERROR: Skipped EndIfDirectiveTrivia
                #End If
                */
                return defaultInstance;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("Microsoft Sans Serif, 15.75pt, style=Bold")]
        [System.Configuration.SettingsManageability(System.Configuration.SettingsManageability.Roaming)]
        public Font CurrentFont
        {
            get
            {
                return (Font)this["CurrentFont"];
            }
            set
            {
                this["CurrentFont"] = value;
            }
        }

        [System.Configuration.ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("Microsoft Sans Serif, 15.75pt, style=Bold")]
        public Font DefaultFont
        {
            get
            {
                return (Font)this["DefaultFont"];
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("https://sppbc.herbivore.site/api")]
        public string BaseUrl
        {
            get
            {
                return Conversions.ToString(this["BaseUrl"]);
            }
            set
            {
                this["BaseUrl"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("Wz^8Ne3f3jnkX#456BTd^$#mJqBE!G")]
        public string ApiPassword
        {
            get
            {
                return Conversions.ToString(this["ApiPassword"]);
            }
            set
            {
                this["ApiPassword"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("Preachy2034")]
        public string ApiUsername
        {
            get
            {
                return Conversions.ToString(this["ApiUsername"]);
            }
            set
            {
                this["ApiUsername"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("True")]
        [System.Configuration.SettingsManageability(System.Configuration.SettingsManageability.Roaming)]
        public bool UpgradeRequired
        {
            get
            {
                return Conversions.ToBoolean(this["UpgradeRequired"]);
            }
            set
            {
                this["UpgradeRequired"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.SettingsManageability(System.Configuration.SettingsManageability.Roaming)]
        public User User
        {
            get
            {
                return (SPPBC.M3Tools.Types.User)this["User"];
            }
            set
            {
                this["User"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        [System.Configuration.SettingsManageability(System.Configuration.SettingsManageability.Roaming)]
        public string Username
        {
            get
            {
                return Conversions.ToString(this["Username"]);
            }
            set
            {
                this["Username"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        [System.Configuration.SettingsManageability(System.Configuration.SettingsManageability.Roaming)]
        public string Password
        {
            get
            {
                return Conversions.ToString(this["Password"]);
            }
            set
            {
                this["Password"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        [System.Configuration.SettingsManageability(System.Configuration.SettingsManageability.Roaming)]
        public bool KeepLoggedIn
        {
            get
            {
                return Conversions.ToBoolean(this["KeepLoggedIn"]);
            }
            set
            {
                this["KeepLoggedIn"] = value;
            }
        }

        [System.Configuration.ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("Count: {0}")]
        public string CountTemplate
        {
            get
            {
                return Conversions.ToString(this["CountTemplate"]);
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        public string Setting
        {
            get
            {
                return Conversions.ToString(this["Setting"]);
            }
            set
            {
                this["Setting"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("Test")]
        public string Test
        {
            get
            {
                return Conversions.ToString(this["Test"]);
            }
            set
            {
                this["Test"] = value;
            }
        }
    }
}

namespace MediaMinistry.My
{

    [HideModuleName()]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal static class MySettingsProperty
    {

        [System.ComponentModel.Design.HelpKeyword("My.Settings")]
        internal static MySettings Settings
        {
            get
            {
                return MySettings.Default;
            }
        }
    }
}
