// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:4.0.30319.42000
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------


using System.Diagnostics;
using Microsoft.VisualBasic;

namespace SPPBC.M3Tools.My.Resources
{

    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [HideModuleName()]
    internal static class Resources
    {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("SPPBC.M3Tools.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to https://sppbc.hopto.org/manager/setup.exe.
        /// </summary>
        internal static string AppUpdateUri
        {
            get
            {
                return ResourceManager.GetString("AppUpdateUri", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BannerImage
        {
            get
            {
                var obj = ResourceManager.GetObject("BannerImage", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BoldOption
        {
            get
            {
                var obj = ResourceManager.GetObject("BoldOption", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] credentials
        {
            get
            {
                var obj = ResourceManager.GetObject("credentials", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to &lt;!Doctype html&gt;
        /// &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; href=&quot;https://sppbc.hopto.org/css/emails.css&quot;&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        ///        &lt;p&gt;Blessings To You {0},&lt;/p&gt;
        /// 
        /// 		&lt;p&gt;Welcome to the St. Paul Primitive Baptist Church Email Listening Ministry. Thank you for becoming a Subscriber. You will receive Sunday&apos;s Messages from the St. Paul Primitive Baptist Church, Austin, TX. Morning Service each week; where Elder Bryon K. Miller is the Pastor. You will Receive your Sunday Morning Message within 2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultNewListenerEmail
        {
            get
            {
                return ResourceManager.GetString("DefaultNewListenerEmail", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        /// &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; href=&quot;https://sppbc.hopto.org/css/emails.css&quot; /&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        /// 
        /// 	&lt;p&gt;Greetings {0},&lt;/p&gt;
        /// 
        ///        &lt;p&gt;Thank you for your blessing of {1:C} for {2}.&lt;/p&gt;
        /// 
        /// 		&lt;p&gt;Thank You For Your Support.&lt;/p&gt;
        /// 
        /// 		&lt;p&gt;Be Blessed.&lt;/p&gt;
        /// 
        /// 		&lt;p class=&quot;center&quot;&gt;&lt;strong&gt;WE LOVE YOU AND AIN&apos;T NOTHING YOU CAN DO ABOUT IT!&lt;/strong&gt;&lt;br&gt;&lt;/p&gt;
        /// 
        /// 		&lt;hr&gt;
        /// 		
        /// 		&lt;p&gt;&lt;strong&gt;Elder Bryon K Miller, Pastor&lt;/strong&gt;&lt;br&gt;
        /// 		St. Paul Primitive Baptist Church&lt;br&gt;
        /// 		Ema [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultReceiptEmail
        {
            get
            {
                return ResourceManager.GetString("DefaultReceiptEmail", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        /// &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; href=&quot;https://sppbc.hopto.org/css/emails.css&quot; /&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        ///        &lt;p&gt;Good Afternoon {0},&lt;/p&gt;
        /// 
        ///        &lt;p&gt;&lt;em&gt;Watch all our sermons on &lt;a href=&quot;https://www.youtube.com/channel/UCJ2c3QAAYu2KneiTvjRJEKg/videos&quot;&gt;YouTube&lt;/a&gt; and subscribe for easier access.&lt;/em&gt;&lt;/p&gt;
        ///        &lt;p&gt;Also, give us a follow on &lt;a href=&quot;https://facebook.com/bryon.miller436&quot;&gt;Facebook&lt;/a&gt;, where we host our weekly live streams&lt;/p&gt;
        ///        &lt;p&gt;You may gi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultSermonEmail
        {
            get
            {
                return ResourceManager.GetString("DefaultSermonEmail", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete
        {
            get
            {
                var obj = ResourceManager.GetObject("delete", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to &lt;p&gt;&lt;a href=&quot;{1}&quot;&gt;{0}&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        internal static string DriveLinkAttachment
        {
            get
            {
                return ResourceManager.GetString("DriveLinkAttachment", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to https://drive.google.com/file/d/{0}/view?usp=sharing.
        /// </summary>
        internal static string DriveShareLink
        {
            get
            {
                return ResourceManager.GetString("DriveShareLink", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit
        {
            get
            {
                var obj = ResourceManager.GetObject("edit", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to ^[_a-z0-9-]+(.[a-z0-9-]+)@[a-z0-9-]+(.[a-z0-9-]+)*(.[a-z]{2,4})$.
        /// </summary>
        internal static string EmailRegex
        {
            get
            {
                return ResourceManager.GetString("EmailRegex", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to ^[a-zA-Z0-9_!#$%&amp;’*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$.
        /// </summary>
        internal static string EmailRegex2
        {
            get
            {
                return ResourceManager.GetString("EmailRegex2", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ErrorImage
        {
            get
            {
                var obj = ResourceManager.GetObject("ErrorImage", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FontOption
        {
            get
            {
                var obj = ResourceManager.GetObject("FontOption", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HidePasswordIcon
        {
            get
            {
                var obj = ResourceManager.GetObject("HidePasswordIcon", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap import
        {
            get
            {
                var obj = ResourceManager.GetObject("import", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Name,Email
        /// John Doe,johndoe@domain.ext
        /// .
        /// </summary>
        internal static string Import_Listeners_Template
        {
            get
            {
                return ResourceManager.GetString("Import_Listeners_Template", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ItalicOption
        {
            get
            {
                var obj = ResourceManager.GetObject("ItalicOption", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to https://sppbc.hopto.org/manager/version.
        /// </summary>
        internal static string LatestAppVersionUri
        {
            get
            {
                return ResourceManager.GetString("LatestAppVersionUri", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Loading_Loop
        {
            get
            {
                var obj = ResourceManager.GetObject("Loading_Loop", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Loading_Loop_3
        {
            get
            {
                var obj = ResourceManager.GetObject("Loading_Loop_3", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logout
        {
            get
            {
                var obj = ResourceManager.GetObject("Logout", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NewDocumentOption
        {
            get
            {
                var obj = ResourceManager.GetObject("NewDocumentOption", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&amp;])[A-Za-z\d@$!%*?&amp;]{8,}$.
        /// </summary>
        internal static string PasswordRegex
        {
            get
            {
                return ResourceManager.GetString("PasswordRegex", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to ^(?:(?:\+?1\s*(?:[.-]\s*)?)?(?:\(\s*([2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9])\s*\)|([2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9]))\s*(?:[.-]\s*)?)?([2-9]1[02-9]|[2-9][02-9]1|[2-9][02-9]{2})\s*(?:[.-]\s*)?([0-9]{4})(?:\s*(?:#|x\.?|ext\.?|extension)\s*(\d+))?$.
        /// </summary>
        internal static string PhoneRegex
        {
            get
            {
                return ResourceManager.GetString("PhoneRegex", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap send_email
        {
            get
            {
                var obj = ResourceManager.GetObject("send-email", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShowPasswordIcon
        {
            get
            {
                var obj = ResourceManager.GetObject("ShowPasswordIcon", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StrikeThruOption
        {
            get
            {
                var obj = ResourceManager.GetObject("StrikeThruOption", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UnderlineOption
        {
            get
            {
                var obj = ResourceManager.GetObject("UnderlineOption", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }
    }
}