// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:4.0.30319.42000
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------


using System.Diagnostics;
using System.Drawing;
using Microsoft.VisualBasic;

namespace MediaMinistry.My.Resources
{

    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [HideModuleName()]
    internal static class Resources
    {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("MediaMinistry.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon App_Icon
        {
            get
            {
                var obj = ResourceManager.GetObject("App_Icon", resourceCulture);
                return (Icon)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap BannerImage
        {
            get
            {
                var obj = ResourceManager.GetObject("BannerImage", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Count: {0}.
        /// </summary>
        internal static string CountTemplate
        {
            get
            {
                return ResourceManager.GetString("CountTemplate", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] credentials
        {
            get
            {
                var obj = ResourceManager.GetObject("credentials", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        /// &lt;html&gt;
        /// &lt;head&gt;
        /// &lt;link rel=&quot;stylesheet&quot; href=&quot;https://sppbc.herbivore.site/manager/css/emails.css&quot;
        /// &lt;/head&gt;
        /// &lt;body&gt;
        /// 
        /// &lt;p&gt;Hello {0},&lt;/p&gt;&lt;br&gt;
        /// 
        /// {1}
        /// &lt;hr&gt;
        /// 
        /// &lt;p&gt;&lt;strong&gt;Elder Bryon K Miller, Pastor&lt;/strong&gt;&lt;br&gt;
        /// 		St. Paul Primitive Baptist Church&lt;br&gt;
        /// 		Email Listening Ministry&lt;br&gt;
        /// 		2209 East 14th Street&lt;br&gt;
        /// 		Austin, TX. 78702&lt;/p&gt;
        /// &lt;/body&gt;
        /// &lt;/html&gt;.
        /// </summary>
        internal static string customMessageTemplate
        {
            get
            {
                return ResourceManager.GetString("customMessageTemplate", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        /// &lt;html&gt;
        /// &lt;head&gt;
        /// &lt;link rel=&quot;stylesheet&quot; href=&quot;https://sppbc.herbivore.site/manager/css/emails.css&quot;
        /// &lt;/head&gt;
        /// &lt;body&gt;
        /// 
        /// &lt;p&gt;Hello {0},&lt;/p&gt;&lt;br&gt;
        /// 
        /// {1}&lt;br&gt;
        /// 
        /// &lt;a href=&quot;{2}&quot;&gt;Drive File&lt;/a&gt;
        /// 
        /// &lt;hr&gt;
        /// 
        /// &lt;p&gt;&lt;strong&gt;Elder Bryon K Miller, Pastor&lt;/strong&gt;&lt;br&gt;
        /// 		St. Paul Primitive Baptist Church&lt;br&gt;
        /// 		Email Listening Ministry&lt;br&gt;
        /// 		2209 East 14th Street&lt;br&gt;
        /// 		Austin, TX. 78702&lt;/p&gt;
        /// &lt;/body&gt;
        /// &lt;/html&gt;.
        /// </summary>
        internal static string customMessageWithDriveLink
        {
            get
            {
                return ResourceManager.GetString("customMessageWithDriveLink", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to &lt;a href=&quot;&quot;{0}&quot;&quot; class=&quot;&quot;drive-link&quot;&quot;&gt;{1}&lt;/a&gt;.
        /// </summary>
        internal static string DriveLinkHtml
        {
            get
            {
                return ResourceManager.GetString("DriveLinkHtml", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to https://drive.google.com/file/d/{0}/view?usp=sharing.
        /// </summary>
        internal static string DriveShareLink
        {
            get
            {
                return ResourceManager.GetString("DriveShareLink", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ErrorImage
        {
            get
            {
                var obj = ResourceManager.GetObject("ErrorImage", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap HidePasswordIcon
        {
            get
            {
                var obj = ResourceManager.GetObject("HidePasswordIcon", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Loading_Loop
        {
            get
            {
                var obj = ResourceManager.GetObject("Loading_Loop", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Loading_Loop_2
        {
            get
            {
                var obj = ResourceManager.GetObject("Loading_Loop_2", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Loading_Loop_3
        {
            get
            {
                var obj = ResourceManager.GetObject("Loading_Loop_3", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Logout
        {
            get
            {
                var obj = ResourceManager.GetObject("Logout", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to &lt;!Doctype html&gt;
        /// &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; href=&quot;https://sppbc.herbivore.site/manager/css/emails.css&quot;&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        ///        &lt;p&gt;Blessings To You {0},&lt;/p&gt;
        /// 
        /// 		&lt;p&gt;Welcome to the St. Paul Primitive Baptist Church Email Listening Ministry. Thank you for becoming a Subscriber. You will receive Sunday&apos;s Messages from the St. Paul Primitive Baptist Church, Austin, TX. Morning Service each week; where Elder Bryon K. Miller is the Pastor. You will Receive your Sunday Morning Mes [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string newListener
        {
            get
            {
                return ResourceManager.GetString("newListener", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        /// &lt;html&gt;
        /// &lt;head&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;https://sppbc.herbivore.site/manager/css/emails.css&quot; /&gt;
        /// &lt;/head&gt;
        /// &lt;body&gt;
        ///    &lt;div&gt;
        ///      &lt;p&gt;Blessings To You, {0}&lt;/p&gt;
        /// 
        /// 
        ///      &lt;p&gt;
        ///        Welcome to the new &lt;strong&gt;BK &amp; AR Miller Ministries Email Listening&lt;/strong&gt;, formerly St. Paul Primitive Baptist Church Email Listening Ministry. Thank you for being a subscriber.
        ///        Over the last year I suffered a major stroke, but thanks be to God, I am still here and alive!
        ///        M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string newSermon
        {
            get
            {
                return ResourceManager.GetString("newSermon", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to ^(?:(?:\+?1\s*(?:[.-]\s*)?)?(?:\(\s*([2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9])\s*\)|([2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9]))\s*(?:[.-]\s*)?)?([2-9]1[02-9]|[2-9][02-9]1|[2-9][02-9]{2})\s*(?:[.-]\s*)?([0-9]{4})(?:\s*(?:#|x\.?|ext\.?|extension)\s*(\d+))?$.
        /// </summary>
        internal static string PhoneRegex
        {
            get
            {
                return ResourceManager.GetString("PhoneRegex", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to &lt;!Doctype html&gt;
        /// &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; href=&quot;https://sppbc.herbivore.site/manager/css/emails.css&quot;&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        /// 
        /// 	&lt;p&gt;Greetings {0},&lt;/p&gt;
        /// 
        ///        &lt;p&gt;Thank you for your blessing of {1:C} for {2}.&lt;/p&gt;
        /// 
        /// 		&lt;p&gt;Thank You For Your Support.&lt;/p&gt;
        /// 
        /// 		&lt;p&gt;Be Blessed.&lt;/p&gt;
        /// 
        /// 		&lt;p class=&quot;center&quot;&gt;&lt;strong&gt;WE LOVE YOU AND AIN&apos;T NOTHING YOU CAN DO ABOUT IT!&lt;/strong&gt;&lt;br&gt;&lt;/p&gt;
        /// 
        /// 		&lt;hr&gt;
        /// 		
        /// 		&lt;p&gt;&lt;strong&gt;Elder Bryon K Miller, Pastor&lt;/strong&gt;&lt;br&gt;
        /// 		St. Paul Primitive Baptist Church [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string receipt
        {
            get
            {
                return ResourceManager.GetString("receipt", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ShowPasswordIcon
        {
            get
            {
                var obj = ResourceManager.GetObject("ShowPasswordIcon", resourceCulture);
                return (Bitmap)obj;
            }
        }
    }
}